```{r setup, include=FALSE}
# set global chunk options
library(knitr)
opts_chunk$set(cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE)
# import funtions
source("functions.R")
load("ic_ec.Rdata")
```
  
Regression of antibody titer vs. age
------------------------------------

<a id="rlm_fit"></a>
## Analysis of antibody titer: robust linear regression
In the following, we fit a robust linear model to the relation:
antibody-titer vs. age. Lots of plots.

### IC50
```{r plot_ic50, dpi=96, message=FALSE}
range_here <- c(0, 4.7)
hp <- plot_antibody(ic_data, "H1_brisbane_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h1_brisbane")

hp <- plot_antibody(ic_data, "H1_PR8_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h1_pr8")

hp <- plot_antibody(ic_data, "H2_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h2")

hp <- plot_antibody(ic_data, "H3_brisbane_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h3_b")

hp <- plot_antibody(ic_data, "H3_HK_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h3_hk")

hp <- plot_antibody(ic_data, "H4_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h4")

range_here <- c(-20, 75)
hp <- plot_antibody(ic_data, "H5_1st_dil_percent", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h5_dil")

hp <- plot_antibody(ic_data, "H7_1st_dil_percent", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp, "ic_h7_dil")
```

----

### EC50
```{r plot_ec50, dpi=96, message=FALSE}
range_here <- c(-1, 4.8)
hp <- plot_antibody(ec_data, "H1_pdm09_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h1pdm09")

hp <- plot_antibody(ec_data, "H1_PR8_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h1pr8")

hp <- plot_antibody(ec_data, "H2_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h2")

hp <- plot_antibody(ec_data, "H3_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h3")

hp <- plot_antibody(ec_data, "H4_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h4")

hp <- plot_antibody(ec_data, "H5_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h5")

hp <- plot_antibody(ec_data, "H7_vir_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h7_vir")

hp <- plot_antibody(ec_data, "H7_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h7")

hp <- plot_antibody(ec_data, "H12_log", smooth_method="rlm", yrange=range_here)
hp
ExportPlot(hp,  "ec_h12")
```

----

### Difference between IC50 and EC50, vs age
Her we plot the IC50 value minus EC50 vs. age and a loess smoothing.
```{r merge_and_delta, dpi=96}
tmp <- merge(ic_data, ec_data, by="donorID")
ic_ec_data <- data.frame(donorID=tmp$donorID, age=tmp$age.x, shot=tmp$shot.x)
ic_ec_data$delta_H1_PR8 <- tmp$H1_PR8_log.x - tmp$H1_PR8_log.y
ic_ec_data$delta_H2 <- tmp$H2_log.x - tmp$H2_log.y
ic_ec_data$delta_H4 <- tmp$H4_log.x - tmp$H4_log.y
rm(tmp)
plot_antibody(ic_ec_data, "delta_H1_PR8", smooth_method="loess")
plot_antibody(ic_ec_data, "delta_H2", smooth_method="loess")
plot_antibody(ic_ec_data, "delta_H4", smooth_method="loess")
```

## _Latest update: 6 May 2013_.
