```{r setup, include=FALSE}
# set global chunk options
library(knitr)
opts_chunk$set(cache=TRUE, echo=FALSE, warning=FALSE, message=FALSE)
# import funtions
source("functions.R")
load("ic_ec.Rdata")
```

Prediction
----------


<a id="pred"></a>
## Prediction
First of all, it might be instructive to look at a matrix scatterplot of all
data. Here below they plots, separated by group just to reduce cluttering.
### IC50
```{r pairs_ic}
library(car)
scatterplotMatrix( ~ H1_brisbane_log + H1_PR8_log + H2_log,
                   data=ic_data, smoother.args=list(span=0.5), main="Group 1")

scatterplotMatrix( ~ H3_brisbane_log + H3_HK_log + H4_log,
                   data=ic_data, smoother.args=list(span=0.5), main="Group 2")

```

### EC50
```{r pairs_ec}
scatterplotMatrix( ~ H1_PR8_log + H1_pdm09_log + H2_log + H12_log + H5_log,
                   data=ec_data, smoother.args=list(span=0.5), main="Group 1")

scatterplotMatrix( ~ H3_log + H4_log + H7_log + H7_vir_log,
                   data=ec_data, smoother.args=list(span=0.5), main="Group 2")

```
<a id="test_h2"></a>
## Test on EC50, H2 strain

If we perform a t-test on effective concentration for H2, we do observe a
difference between vaccinated and non vaccinated.

```{r test_h2, echo=TRUE}
t.test(H2_log ~ shot, data=ec_data)
```

On the other hand, the difference is all explained by the fact that we are
not controlling for the age. In fact, if we perform ANCOVA, age is significant,
while age is not.

```{r aov_h2, echo=TRUE}
fit_aov <- aov(H2_log ~ age + factor(shot), data=ec_data)
summary(fit_aov)
```
This is because the average age in the vaccinated is higher (42 vs. 35).
```{r test_age, echo=TRUE}
t.test(age ~ shot, data=ec_data)
```

Let's make less assumption: we fit with `glm` (that allows for non-constant
variance), and we include an interaction term.

```{r glm_h2, echo=TRUE}
glm_fit <- glm(H2_log ~ age * factor(shot), data=ec_data)
summary(glm_fit)
```
The situation does not exactly get better: we have all terms significant
(albeit not by much), but the shot status coefficient alone is negative. As a
consequence, the vaccination gives a positive contribution to the EC50 only
for donors older than 36. Overall, we don't observe a clear and univoque
contribution from the vaccination, while the effect of the age is clear.

In conclusion, I would only consider the age as effective on the titer.

----

## _Latest update: 27 April 2013_.
